export const GET_PRODUCTS_REQUESTED = "GET_PRODUCTS_REQUESTED";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";
export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const UNSELECT_PRODUCT = "UNSELECT_PRODUCT";
